name: Run Python Script

on:
 workflow_dispatch:
 push:
  branches:
    - main   

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your desired Python version

      - name: Run Python Script
        run: python test.py
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print All Variables
        run: |
          env
  print-collected-data:
    needs: run-script
    runs-on: ubuntu-latest

    steps:
      - name: Collect Data
        run: |
           echo ${{ github.workflow }}
           echo ${{ github.run_id}}
           echo ${{ github.ref }}
           
